[tool.poetry]
name = "jmeslog"
version = "0.1.1"
description = "Tool for managing changelogs"
authors = [
    "James Saryerwinnie <js@jamesls.com>",
]
license = "Apache-2.0"
readme = "README.md"

documentation = "https://jamesls.github.io/jmeslog"
homepage = "https://jamesls.github.io/jmeslog"
repository = "https://github.com/jamesls/jmeslog"

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

packages = [
    { include = "jmeslog", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.9.0, <4.0"
Jinja2 = "^3.1.2"
packaging = "^24.0"

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
flake8-comprehensions = "*"
flake8-logging-format = "*"
isort = "*"
mypy = "*"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
mkdocstrings = "*"
mkdocs-material = "*"
pymdown-extensions = "*"
pytest-github-actions-annotate-failures = "*"
poethepoet = "*"
pylint = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 79
honor_noqa = true
src_paths = ["src", "tests"]

[tool.black]
target-version = ["py39"]
include = '\.pyi?$'
line-length = 79
skip_string_normalization = true

[tool.pytest.ini_options]
addopts = """\
    --cov jmeslog \
    --cov tests \
    --cov-report term-missing \
    --no-cov-on-fail \
"""

[tool.coverage.report]
# Bump this up as we add coverage
fail_under = 77
exclude_lines = [
    'if TYPE_CHECKING:',
    'pragma: no cover'
]

[tool.mypy]
disallow_any_unimported = true
disallow_untyped_defs = true
no_implicit_optional = true
strict_equality = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
check_untyped_defs = true
show_error_codes = true
exclude = ['tests/']


[tool.poe.tasks]
pre-commit = "poetry run pre-commit run --all-files"
test = "poetry run pytest tests/"
stage-release = "python3 ./scripts/stage-release --output staged-release.zip"
format-code = [
  { cmd = "poetry run black ." },
  { cmd = "poetry run isort ." },
]
prcheck = ["pre-commit", "test"]

[tool.poetry.scripts]
jmeslog = "jmeslog.cli:main"
